FORMAT: 1A
HOST: https://snapbundle.tagdynamics.net

# SnapBundle API
SnapBundle is a platform purposefully built to be an application's contextual data store.

# Registration Notes
Registering for an SnapBundle Account and then confirming the email address associated with the Account registration are the only perquisites for using the platform. These two steps are required before any endpoints that require authentication can be successfully accessed.

## Security Realm [/registration/realm/{realm}]
### Check Realm Availability [GET]

+ Parameters
    + realm (required, string, `foo.com`) ... Check to see if the named realm is available for registration

+ Response 200 (application/json)

        {
          "result": 0, 
          "message": "foo.com"
        }

## Account Registration [/registration/register]
### Register for a new SnapBundle account

+ Request (application/json)

        { "emailAddress": "you@foo.com", "realm" : "foobar.com" }

+ Response 200 (application/json)

        {
                "urn" : "urn:uuid:64618d0b-3b8c-456a-87d0-31bc1a0bc579",
                "lastModifiedTimestamp" : 1382828220349,
                "emailAddress" : "you@foo.com",
                "realm" : "foo.com",
        }
