language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: XzKQEMkgI3/EayoWWz28zGPpHSkXywNQWbYNpYMD0o2MXqm3b+E1PwGs9JS1lYbq0/Yob/CYuV9D9Z0oP8030UjtE0ZwK1veM8sxlQmPh1cVwHDw/OXk9lEFWSyNF3g3VeaRsP5F8toLhP8LQHUyvjQyVd6tfMaR84D8+KcWKk1NV/ARAC4g05wm8TVhE1suR0BnvMJdqkyTYziDR9l+cKU4ds7kbI1+3OryUuYH8VGKuz4a1AgYNoZhZaXKgARCEY63YDMiXjkMao1HsObIogrS+qBrKXlPm/rgJZ0VpPcW6C4p2MOZ1zn3TOP1pGr5b8lwaqCFRyEIj6opw1t4t7AZDTWIthMMtENxx6i74g/iBe7QkkkWTNEChEfF/hUJalSsFoY2QOJsVaRPSvNMc9mVPtjGbgBmC5cZZZ7uOpLDEn5SDa3LgzbDSVVLdR2VdfWdLYnV3fIjGQAUXvpw215QkwoUC/3VQhzMMKs3pHmMUlgIAXx1fBggyfoe9GS1woUtQ9J1qhxKKuk10x/mzoEBpxdJpTLuvhrJL5QmXISxCAfU1gsuNyXh86044wdV+ZQPDAITxEb0ztNuRVTNfpg6g4ST8lmq5VwEllm6cVPaF3uBfhzw/4X2jLkB5k/uf2YhU4Fur7zBUJzb3C3H4d9eOTCXBFhFIHtDtGO/IAU=
