= Contributing to SMART COSMOS

SMART COSMOS Framework is released under the Apache 2.0 license.  SMART COSMOS Objects is a platform designed to easily capture all types of data, especially relationships and interactions, from today's always-on sensors, smart devices, and automated workflows. Enriched data, including multimedia, can be easily fed into various back office systems in near real-time using simple web integration techniques.  Due to the massive amount of integrations and extensions into SMART COSMOS we welcome contributions and feedback on our Extension API in particular.

== Issue Tracking

To be determined.  We'll get back to you.  We use JIRA, just need to find a place to publicly submit issues.

== Code Conventions

If you want to build an extension then there's no need to follow our format, but if you want to contribute to any of our public repositories then it's required.

See the build-tools jar for eclipse formatting.

== Additional Resources
* https://smartractechnology.atlassian.net/wiki/display/SCKB/SMART+COSMOS+Developer+Knowledge+Base[SMART COSMOS Developer Knowledge Base]
* http://help.github.com/[General GitHub documentation]
* http://help.github.com/send-pull-requests/[GitHub pull request documentation]
* http://docs.smartcosmosobjects.apiary.io[Objects REST Web Services Documentation]
* http://smartractechnology.github.io/smartcosmos-sdk-java/stable/index.html[SMART COSMOS Java SDK JavaDocs (stable)]
