= SMART COSMOS Getting Started Guide
SMARTRAC Technology Fletcher Inc <api@smartrac-group.com>
:version: 3.0.1-SNAPSHOT
ifdef::env-github[:USER: SMARTRACTECHNOLOGY]
ifdef::env-github[:REPO: smartcosmos-framework]
ifdef::env-github[:BRANCH: master]

image::https://travis-ci.org/{USER}/{REPO}.svg?branch={BRANCH}[Build Status, link=https://travis-ci.org/{USER}/{REPO}]

== Welcome to SMART COSMOS
Welcome to SMART COSMOS!

Are you ready to become part of creating something really big? With SMART COSMOS
you can connect a universe of everyday things to the digital world. In fact,
SMART COSMOS is the only platform that is purely focused on providing a fast
track for both enterprises and developers to Monetize the IoT.

SMART COSMOS is an ecosystem. It consists of a robust partner network where
hardware manufacturers, system integrators, software developers and enterprises
come together to create the IoT. It is comprised of both SaaS and PaaS offerings
that help you EMBED, ENRICH, EFFECT, and EXPLORE IoT driven data.

SMART COSMOS also includes an education portal,
*http://lessons.smart-cosmos.com[SMART COSMOS Lessons]*, and a
vibrant developer community at our
*https://partner.smart-cosmos.com[Partner Development Portal]*. Developers who
complete the full Extension Developer learning path, passing all exams, earn the
right and privileges of being a SMART COSMOS Certified Engineer.

In order to accelerate value creation with the IoT, enterprises must learn how
to obtain new value from four key areas:

* Data
* Things
* People
* Process

The IoT is nothing more than combining a creative mixture of low-cost sensing
hardware, auto-identification technologies like RFID, and the Cloud! Now, we
invite you to take the next steps and learn how to use our proven blueprint to
*Monetize the IoT*.

*EXPLORE* the full capabilities of the entire ecosystem by participating in one or
more Web based learning paths at SMART COSMOS Lessons.

*CREATE* new and innovative IoT Mashups by building Extensions that perform an
IaaS Cloud Pivot or integrate new applications, features, and REST Web services
into the platform.

*SELL* innovative Extensions at the SMART COSMOS Market by defining the level of
support provided, marketing materials, manuals, and of course an appropriate
recurring revenue model.

Finally, platforms are living designs that are always evolving. If you have
feedback, feature requests, or just want to meet for some drinks and talk
software design patterns, contact us either at the developer portal or via
email: mailto:api@smartrac-group.com[api@smartrac-group.com]


== SMART COSMOS Objects License
You must review and accept the
https://licensing.smartcosmos.net/objects/[SMART COSMOS Objects EULA] before
working with this developer kit.

== Open Source Development Framework
SMART COSMOS includes a number of open sourced frameworks available under the
Apache License, Version 2. You can clone freely use these frameworks in your
projects, submit pull requests, and access the latest documentation at GitHub:

https://github.com/SMARTRACTECHNOLOGY/smartcosmos-framework

IMPORTANT: The core of the Objects server itself is proprietary and must be
properly licensed when deployed in a production environment.

In addition to the open source development framework, the entirety of the
SMART COSMOS REST Web Service APIs are fully documented at our API web site,
http://api.smartcosmos.net

== SMART COSMOS Lessons: Get Certified
Software developers have the opportunity to complete the Extension Developer
learning path at our education portal, SMART COSMOS Lessons. Upon completing
about 14 hours of self-paced web courses and passing all of the exams, you
establish yourself as SMART COSMOS expert and have the ability to promote your
expertise at the https://partner.smart-cosmos.com[Partner Development Portal].

TIP: You need a code to complete the
http://lessons.smart-cosmos.com/self-signup[SMART COSMOS Lessons self-signup].
If you don't have one, just ask for one by dropping us an email at
mailto:api@smartrac-group.com[api@smartrac-group.com].

== Partner Development Portal
The https://partner.smart-cosmos.com[Partner Development Portal] is the online
community for all things SMART COSMOS. Here you can review partner profiles,
developer profiles, access technical white papers, review technical use cases,
register for contests, and much more. If you haven't already, you should visit
the site and register as a developer to gain access to more technical data
about the SMART COSMOS platform and network with other professionals using
SMART COSMOS to Monetize the IoT.

== Maven Central
Java developers that rely on Maven Central can access the SMART COSMOS
libraries by searching for groupId of *net.smartcosmos*.:

The http://search.maven.org/#artifactdetails%7Cnet.smartcosmos%7Csmartcosmos-framework%7C{version}%7Cjar[core framework]
has the following coordinates:

[source,xml,subs="attributes,verbatim"]
--
<dependency>
  <groupId>net.smartcosmos</groupId>
  <artifactId>smartcosmos-framework</artifactId>
  <version>{version}</version>
</dependency>
--

To make it easier to develop an extension, we also provide a parent POM file that you can extend:

[source,xml,subs="attributes,verbatim"]
--
<parent>
    <groupId>net.smartcosmos</groupId>
    <artifactId>smartcosmos-framework-parent</artifactId>
    <version>{version}</version>
    <relativePath></relativePath>
</parent>
--

And in the event you already have a parent structure, we provide a dependency POM file that you can import:

[source,xml,subs="attributes,verbatim"]
--
<dependencyManagement>
     <dependencies>
        <dependency>
            <!-- Import dependency management -->
            <groupId>net.smartcosmos</groupId>
            <artifactId>smartcosmos-framework-dependencies</artifactId>
            <version>{version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>
--

TIP: Remember, the artifacts in Maven Central are *living* artifacts and will
have new releases from time to time. You are *strongly encouraged* to visit
http://search.maven.org/#search%7Cga%7C1%7Cg%3Anet.smartcosmos[https://search.maven.org]
to find the latest version after {version}.amp

== For More Information

See github.
